### PR TITLE
Remove lexical-binding, which is unused and implies an Emacs 24 dependency

### PR DESCRIPTION
**Pull request by purcell**
Thought I'd go ahead and add this to MELPA...

### CODE REVIEW

**Comment by jordonbiondo** [comment]
I'm unfamiliar with MELPA packages that include non elisp tools, there is not a way to start the server or documentation for how to in the elisp itself, is this an issue?

**Comment by purcell** [comment]
I suppose it's not ideal. You could (should?) probably provide an emacs command which runs the server in the background in a buffer.

**Comment by jordonbiondo** [comment]
Indeed, I've added the ability to start it from emacs, as well checks and messages for requiring macruby. I am assuming the name is enough to denote the need for osx.

**Comment by purcell** [comment]
> Indeed, I've added the ability to start it from emacs, as well checks and messages for requiring macruby.

Great!

> I am assuming the name is enough to denote the need for osx.

I think so. I have an `osx-location` package, which I think is similarly unambiguous.

**Pull request merged**
